apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
    spec:
      conainers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        